### ISSUE TITLE
Glacier transfer does not remove all zip artifacts in hidden directories 

### ISSUE THREAD

**Issue by demery** [upenn-libraries/guardian#44]
Guardian glacier transfer uses `Dir.glob('*')` to remove working files, which misses hidden files and folders:

https://github.com/upenn-libraries/guardian/blob/master/guardian-glacier-transfer#L392

**Comment by kelynch** [comment]
Addressed

**Comment by demery** [comment]
Problem is still not fixed.

**Comment by kelynch** [comment]
Addressed in #46
